### ISSUE TITLE
Investigate Krombacher REST API 401 errors (Salesforce API)

### ISSUE THREAD

**Issue by MykytaDuniashev** [elasticio/rest-api-component-v2#37]
## Description

Krombacher reported that they have a flow where sometimes the REST Call to SF is not working. They said that restarting the flow helps for some period.
The error message: `Code: 401 Message: Unauthorized Body: [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}]`

REST API logs:
```
[2024-02-12 11:15:23.125]: Checking rate limit parameters...
[2024-02-12 11:15:23.167]: Component error
[2024-02-12 11:15:23.174]: Delay Between Calls is not set, process message without delay...
[2024-02-12 11:15:23.175]: processMessage emit end was called more than once
```
Flow configuration:
![image](https://github.com/elasticio/rest-api-component-v2/assets/108279772/27367ea5-0f5c-4bb4-84cb-e46d678c1bff)

It fails on step **6. 6. Salesforce Anonymize Endpoint**.

- [Link](https://app.elastic.io/c/5f350c8df8392d00111c1c40/w/5f350ced82be0b0011871e02/designer/62b16b94f6ef3900119a9003/v/latest) to the flow.
- [Link](https://elasticio.slack.com/archives/C7DMBKG3D/p1599814947354700) to the Slack conversation with a similar problem in REST API v1

## Component Version

2.0.14

## Workaround(s)

Rebuild the flow with the Salesforce component instead of REST API

**Comment by if0s** [comment]
It's not a problem in component.
As I can see from the flow structure, this step `6. Salesforce Anonymize Endpoint` is using data from the previous step `5. Salesforce Auth Token` (Configuration component) for authentication.
I'm assuming that there is some other flow (or something else) that updates data in this Configuration component to store valid Access token, but this data can't be updated inside running flow

The whole process can be described like this:
*  Step `5. Salesforce Auth Token` extracting `Access token` from configuration
*  Step `6. Salesforce Anonymize Endpoint` use `Access token` from previous step
* After some period of time, `Access token` becoming invalid
* Some other flow or mechanism updates `Access token` in configuration
* Step `5. Salesforce Auth Token`  is continuing to use old `Access token` because flow didn't stop/slept - to update it with valid `Access token` there should be new pod created, and it's impossible for real-time flows and problematic if flow doesn't go to `Sleeping` state

In the documentation for Configuration component you can see [this limitation](https://github.com/elasticio/configuration-component?tab=readme-ov-file#known-limitations):
```
As realtime flows use credentials which were saved at the moment of starting the flow, this component should be used only in ordinary flows. This is not a bug or limitation, but the platform specific case.
```
As I can see from executions page, this flow starting really often and even if we make it ordinary, problem will be still there.
Configuration component is not suitable for this case, instead you can use some other storage here - some database for example

**Comment by andrewreshitko** [comment]
@MykytaDuniashev please forward this info to the client and close the task.
Thank you!

**Comment by MykytaDuniashev** [comment]
@if0s Can they use the Salesforce [Raw request](https://docs.elastic.io/components/salesforce/actions#raw-request-action) action as another workaround?

**Comment by if0s** [comment]
@MykytaDuniashev if it's fine for client it would be the best option

**Comment by andrewreshitko** [comment]
Closed as completed.
